// ===== ESV (Earned Social Value) CALCULATOR =====
// Computes the economic value generated by ad slots based on agent interactions

export interface SlotStats {
  impressions: number;
  positiveInteractions: number;
  neutralInteractions: number;
  negativeInteractions: number;
  mentions: number;
}

export interface BrandStats {
  brand: string;
  totalESV: number;
  totalImpressions: number;
  totalMentions: number;
  positiveRatio: number;
  negativeRatio: number;
  slotCount: number;
}

/** Calculate ESV for a single slot based on its stats */
export function calcESV(stats: SlotStats): number {
  // Base value per impression
  const IMPRESSION_VALUE = 0.5;
  // Interaction multipliers
  const POSITIVE_MULT = 3.0;
  const NEUTRAL_MULT = 1.0;
  const NEGATIVE_MULT = -0.5;
  // Mention bonus
  const MENTION_VALUE = 5.0;

  return Math.max(0, Math.round(
    stats.impressions * IMPRESSION_VALUE +
    stats.positiveInteractions * POSITIVE_MULT +
    stats.neutralInteractions * NEUTRAL_MULT +
    stats.negativeInteractions * NEGATIVE_MULT +
    stats.mentions * MENTION_VALUE
  ));
}

/** Aggregate brand-level stats from multiple slots */
export function aggregateBrandStats(
  slotData: Array<{ brand: string; stats: SlotStats }>
): BrandStats[] {
  const map = new Map<string, {
    totalESV: number;
    totalImpressions: number;
    totalMentions: number;
    positive: number;
    neutral: number;
    negative: number;
    slotCount: number;
  }>();

  for (const { brand, stats } of slotData) {
    const existing = map.get(brand) || {
      totalESV: 0, totalImpressions: 0, totalMentions: 0,
      positive: 0, neutral: 0, negative: 0, slotCount: 0,
    };
    existing.totalESV += calcESV(stats);
    existing.totalImpressions += stats.impressions;
    existing.totalMentions += stats.mentions;
    existing.positive += stats.positiveInteractions;
    existing.neutral += stats.neutralInteractions;
    existing.negative += stats.negativeInteractions;
    existing.slotCount += 1;
    map.set(brand, existing);
  }

  return Array.from(map.entries()).map(([brand, d]) => {
    const total = d.positive + d.neutral + d.negative;
    return {
      brand,
      totalESV: d.totalESV,
      totalImpressions: d.totalImpressions,
      totalMentions: d.totalMentions,
      positiveRatio: total > 0 ? d.positive / total : 0,
      negativeRatio: total > 0 ? d.negative / total : 0,
      slotCount: d.slotCount,
    };
  }).sort((a, b) => b.totalESV - a.totalESV);
}
